apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmu-mfe-shell
  labels:
    app: rmu-mfe-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmu-mfe-shell
  template:
    metadata:
      labels:
        app: rmu-mfe-shell
    spec:
      containers:
        - name: rmu-mfe-shell
          image: labcabrera/rmu-mfe-shell:latest
          ports:
            - containerPort: 8080
          env:
            - name: RMU_FE_HOST_PUBLIC_PATH
              valueFrom:
                configMapKeyRef:
                  name: rmu-shared-configmap
                  key: RMU_FE_HOST_PUBLIC_PATH

            - name: RMU_MODULE_FEDERATION_STRATEGIC
              valueFrom:
                configMapKeyRef:
                  name: rmu-shared-configmap
                  key: RMU_MODULE_FEDERATION_STRATEGIC

            - name: RMU_MODULE_FEDERATION_TACTICAL
              valueFrom:
                configMapKeyRef:
                  name: rmu-shared-configmap
                  key: RMU_MODULE_FEDERATION_TACTICAL

            - name: RMU_MODULE_FEDERATION_NPC
              valueFrom:
                configMapKeyRef:
                  name: rmu-shared-configmap
                  key: RMU_MODULE_FEDERATION_NPC

            - name: RMU_API_STRATEGIC_URL
              valueFrom:
                configMapKeyRef:
                  name: rmu-shared-configmap
                  key: RMU_API_STRATEGIC_URL

            - name: RMU_API_CORE_URL
              valueFrom:
                configMapKeyRef:
                  name: rmu-shared-configmap
                  key: RMU_API_CORE_URL
